### ISSUE TITLE
problem of usage

### ISSUE THREAD

**Issue by riyueshi** [cdcseacave/openMVS_sample#1]
Hi, cdcseacave,
  I used three images (which sized 8176*6132 ) as input (processed with visualSFM) the program just crashed while RefineMesh. The program occupied all the memory (8G in my computer) and my computer can nothatt work after that, is there a solution that can handle many high resolution images.

Miller Zhang

**Comment by cdcseacave** [comment]
If the resolution is the issue, you have to downscale it cause currently the scenes can be processed only if they fit completely in memory.
