### ISSUE TITLE
Question about "DensifyPointCloud"

### ISSUE THREAD

**Issue by BooguTeam** [cdcseacave/openMVS_sample#13]
When I follow [openMVS example](https://github.com/cdcseacave/openMVS/wiki/Usage)

After running:
`DensifyPointCloud scene.mvs`

Then when I am running 
`DensifyPointCloud scene.mvs --fusion-mode -1`

An error occurs:

DensifyPointCloud: /home/harry/HW/DD/openMVS/libs/Common/Types.h:1615: int SEACAVE::TDMatrix<TYPE>::area() const [with TYPE = float]: Assertion `dims == 2' failed.
Aborted (core dumped)

**Comment by Li291216576** [comment]
hello, may I know have you solved the problem? I encounter the same, haha

**Comment by Harr7y** [comment]
> hello, may I know have you solved the problem? I encounter the same, haha

No. I just gave up using it.
