### ISSUE TITLE
Not using robust.bin in MvgMvs_Pipeline.py

### ISSUE THREAD

**Issue by lufi0401** [cdcseacave/openMVS_sample#5]
Hi, 
I am using [`MvgMvs_Pipeline.py`](https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py#L122) and notice that `robust.bin` is generated from step "Colorized robust triangulation" but isn't used to export to openMVS (`sfm_data.bin` is used instead):
https://github.com/cdcseacave/openMVS_sample/blob/b119f9b131cbc48870ce65ed4c6693ae7f95f64f/MvgMvs_Pipeline.py#L120-L125
Is that intentional?
Thanks for the help.

**Comment by cdcseacave** [comment]
OpenMVG suffered changes since the moment this script was written, but I did not follow them, so I do not know about the existance of that file and what is suppoed to contain; the best is to ask @pmoulon which is the final SfM scene than should be further used for densification

**Comment by pmoulon** [comment]
Using `sfm_data.bin` is ok.
The `robust.bin` step and file is a optional step that is included in the basic python sample to explain the possibilities of the OpenMVG API.

So basically you can remove those two step:
```
[   "Structure from Known Poses",
                os.path.join(OPENMVG_BIN,"openMVG_main_ComputeStructureFromKnownPoses"),
                ["-i", "%reconstruction_dir%/sfm_data.bin", "-m", "%matches_dir%", "-f", "%matches_dir%/matches.f.bin", "-o", "%reconstruction_dir%/robust.bin"]],
            [   "Colorized robust triangulation",
                os.path.join(OPENMVG_BIN,"openMVG_main_ComputeSfM_DataColor"),
                ["-i", "%reconstruction_dir%/robust.bin", "-o", "%reconstruction_dir%/robust_colorized.ply"]],
```

**Comment by lufi0401** [comment]
Thanks both for the answer!
