### ISSUE TITLE
openMVS_sample params

### ISSUE THREAD

**Issue by LightFieldVision** [cdcseacave/openMVS_sample#7]
@cdcseacave 
First，thank you for providing the openMVS_sample. I have some questions, I use openMVS_sample and OpenMVS program which i compiled  to process the same set of data. When i process the Reconstruct Mesh, the openMVS_sample can obtain a correct result, but OpenMVS program can not.  I guess this may be because the parameter settings of the two are different. Can you help me with the answer or give me a detailed parameter list for the Reconstruct Mesh?
tks!

**Comment by cdcseacave** [comment]
the data saved there is old, not compatible with the latest OpenMVS format
the command lines are the same though
so you need to follow the indicated steps, but starting from the begining, from the images: SfM reconstruction, using whatever u like, like OpenMVS, COLMAP, etc, export it in MVS format (`scene.mvs`) and next use OpenMVS

**Comment by LightFieldVision** [comment]
Sorry, I didn't describe it too clearly. In fact, I use Scene.mvs file, which is generated by the MVG, to build the Scene_dense.mvs. And then I use the OpenMVS_sample and OpenMVS program which I compiled respectively to reconstrut mesh the Scene_dense.mvs file.  But OpenMVS program can not obtain mesh file.

In addition, can you give me your email address? I can send the data to you for the test.
tks!

**Comment by cdcseacave** [comment]
I do not think I understand, if you are using the latest OpenMVS code (develop branch) and you have problems with it, pls create an issue in OpenMVS. You can safely pot any debug data there.

**Comment by LightFieldVision** [comment]
It turns out that the OpenMVS_Sample can handle the Scene_dense.mvs file!

**Comment by LightFieldVision** [comment]
![image](https://user-images.githubusercontent.com/19601392/58400362-5ec19600-808d-11e9-83ec-e3b5a2096f09.png)
Where the red line draws, points weight compute seem to be wrong. Can you help me? thank you
