### ISSUE TITLE
There is no defined intrinsic data in order to compute an essential matrix for the initial pair

### ISSUE THREAD

**Issue by zjbaby** [cdcseacave/openMVS_sample#8]
I build openMVG and openMVS in **ubuntu** successfully, and then I use the images and MvgMvs_Pipeline.py script in openMVS_sample to test reconstruction. However, I can't get right results as the openMVS_sample provided. I encournter an error when execute the "**openMVG_main_IncrementalSfM**": **There is no defined intrinsic data in order to compute an essential matrix for the initial pair.**
 **Why? And what I should do to get  the right results?**

**My operation and run log is as follows:**
root@5fb8fe3efd24:/home/openMVS_sample/test# python ../MvgMvs_Pipeline.py ../images/ ./
# Using input dir  :  /home/openMVS_sample/images
#       output_dir :  /home/openMVS_sample/test
# First step  :  0
# Last step :  11
#0. Intrinsics analysis
 You called : 
/home/openMVG/build/install/bin/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/openMVS_sample/images
--sensorWidthDatabase /home/openMVS_sample/sensor_width_camera_database.txt
--outputDirectory /home/openMVS_sample/test/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 11
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 0
#1. Compute features
 You called : 
/home/openMVG/build/install/bin/openMVG_main_ComputeFeatures
--input_file /home/openMVS_sample/test/matches/sfm_data.json
--outdir /home/openMVS_sample/test/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 4

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 5
#2. Compute matches
 You called : 
/home/openMVG/build/install/bin/openMVG_main_ComputeMatches
--input_file /home/openMVS_sample/test/matches/sfm_data.json
--out_dir /home/openMVS_sample/test/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
#3. Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 6256
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
------------------
TrackLength, Occurrence
	2	3019
	3	1202
	4	644
	5	438
	6	276
	7	253
	8	196
	9	143
	10	79
	11	6

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
#4. Colorize Structure

The input SfM_Data file "/home/openMVS_sample/test/reconstruction_sequential/sfm_data.bin" cannot be read.
#5. Structure from Known Poses
Compute Structure from the provided poses

The input SfM_Data file "/home/openMVS_sample/test/reconstruction_sequential/sfm_data.bin" cannot be read.
#6. Colorized robust triangulation

The input SfM_Data file "/home/openMVS_sample/test/reconstruction_sequential/robust.bin" cannot be read.
#7. Export to openMVS

The input SfM_Data file "/home/openMVS_sample/test/reconstruction_sequential/sfm_data.bin" cannot be read.
#8. Densify point cloud
18:05:41 [App     ] Build date: Jun 20 2019, 17:39:48
18:05:41 [App     ] CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 cores)
18:05:41 [App     ] RAM: 15.53GB Physical Memory 14.90GB Virtual Memory
18:05:41 [App     ] OS: Linux 4.15.0-20-generic (x86_64)
18:05:41 [App     ] SSE & AVX compatible CPU & OS detected
18:05:41 [App     ] Command line: scene.mvs -w /home/openMVS_sample/test/mvs
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
#9. Reconstruct the mesh
18:05:41 [App     ] Build date: Jun 20 2019, 17:39:48
18:05:41 [App     ] CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 cores)
18:05:41 [App     ] RAM: 15.53GB Physical Memory 14.90GB Virtual Memory
18:05:41 [App     ] OS: Linux 4.15.0-20-generic (x86_64)
18:05:41 [App     ] SSE & AVX compatible CPU & OS detected
18:05:41 [App     ] Command line: scene_dense.mvs -w /home/openMVS_sample/test/mvs
18:05:41 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
18:05:41 [App     ] CUDA device 0 initialized: Quadro P600 (compute capability 6.1; memory 3.95GB)
#10. Refine the mesh
18:05:41 [App     ] Build date: Jun 20 2019, 17:39:48
18:05:41 [App     ] CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 cores)
18:05:41 [App     ] RAM: 15.53GB Physical Memory 14.90GB Virtual Memory
18:05:41 [App     ] OS: Linux 4.15.0-20-generic (x86_64)
18:05:41 [App     ] SSE & AVX compatible CPU & OS detected
18:05:41 [App     ] Command line: scene_dense_mesh.mvs -w /home/openMVS_sample/test/mvs
18:05:41 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
18:05:41 [App     ] CUDA device 0 initialized: Quadro P600 (compute capability 6.1; memory 3.95GB)
#11. Texture the mesh
18:05:41 [App     ] Build date: Jun 20 2019, 17:39:48
18:05:41 [App     ] CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 cores)
18:05:41 [App     ] RAM: 15.53GB Physical Memory 14.90GB Virtual Memory
18:05:41 [App     ] OS: Linux 4.15.0-20-generic (x86_64)
18:05:41 [App     ] SSE & AVX compatible CPU & OS detected
18:05:41 [App     ] Command line: scene_dense_mesh_refine.mvs -w /home/openMVS_sample/test/mvs
18:05:41 [App     ] MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
18:05:41 [App     ] CUDA device 0 initialized: Quadro P600 (compute capability 6.1; memory 3.95GB)

**Comment by cdcseacave** [comment]
The sample is to prove the OpenMVS pipeline, not to be used with OpenMVG, and so only the undistorted images and `scene.mvs` files are needed as input. You are free to obtain them in any way you like, for example using OpenMVG on the original images, prior to using OpenMVS.
